import { test, expect } from '@playwright/test';

import { apiLoginAsAdmin, createWebhookIngestErrorViaApi, loginAsAdmin } from './helpers';

test.describe('Ingest Errors', () => {
  test.beforeEach(async ({ page }) => {
    await loginAsAdmin(page);
    await page.goto('/ingest-errors');
  });

  test('can inspect a quarantine item generated by invalid epsilon webhook', async ({ page, request }) => {
    const session = await apiLoginAsAdmin(request);
    const created = await createWebhookIngestErrorViaApi(request, session.access_token);

    await page.getByLabel(/source system do filtro de quarentena/i).fill('ConnectorEpsilon');
    await page.getByRole('button', { name: /atualizar quarentena de ingestão/i }).click();

    await expect(page.getByText(/connectorepsilon/i).first()).toBeVisible({ timeout: 10_000 });
    await page.getByText(/connectorepsilon/i).first().click();

    await expect(page.getByRole('heading', { name: /detalhe da quarentena/i })).toBeVisible({ timeout: 10_000 });
    await expect(page.locator('pre').filter({ hasText: created.marker }).first()).toBeVisible({ timeout: 10_000 });
  });
});
