-- BetAML PostgreSQL Initialization Script
-- Multi-tenant OLTP database schema

-- ===================== SCHEMA CREATION =====================

CREATE SCHEMA IF NOT EXISTS public;

-- ===================== ENUMS =====================

CREATE TYPE user_role_type AS ENUM ('ADMIN', 'AML_ANALYST', 'AUDITOR');
CREATE TYPE rule_status_type AS ENUM ('ACTIVE', 'INACTIVE', 'TESTING');
CREATE TYPE alert_severity_type AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE alert_status_type AS ENUM ('NEW', 'ACK', 'CLOSED', 'ESCALATED');
CREATE TYPE case_status_type AS ENUM ('OPEN', 'UNDER_INVESTIGATION', 'SAR', 'SAT', 'CLOSED');
CREATE TYPE ingest_job_status_type AS ENUM ('QUEUED', 'PROCESSING', 'SUCCESS', 'FAILED');

-- ===================== TABLES =====================

-- Tenants (multi-tenancy root)
CREATE TABLE tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    max_users INT DEFAULT 100,
    data_retention_days INT DEFAULT 365,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tenants_name ON tenants(name);
CREATE INDEX idx_tenants_status ON tenants(status);

-- Users (RBAC)
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role user_role_type NOT NULL,
    is_active BOOLEAN DEFAULT true,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tenant_id, username),
    UNIQUE(tenant_id, email)
);

CREATE INDEX idx_users_tenant ON users(tenant_id);
CREATE INDEX idx_users_role ON users(tenant_id, role);

-- Mapping Configurations (for heterogeneous inputs)
CREATE TABLE mapping_configs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    source_system VARCHAR(255) NOT NULL,
    schema_version INT DEFAULT 1,
    mapping_rules JSONB NOT NULL,  -- { "field_mappings": {...}, "transformations": [...] }
    is_active BOOLEAN DEFAULT true,
    created_by UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tenant_id, source_system, schema_version)
);

CREATE INDEX idx_mapping_configs_tenant ON mapping_configs(tenant_id);
CREATE INDEX idx_mapping_configs_active ON mapping_configs(tenant_id, is_active);

-- Ingest Jobs (tracking file uploads)
CREATE TABLE ingest_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    mapping_config_id UUID NOT NULL REFERENCES mapping_configs(id),
    file_name VARCHAR(255),
    file_size_bytes BIGINT,
    status ingest_job_status_type DEFAULT 'QUEUED',
    row_count INT,
    error_message TEXT,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ingest_jobs_tenant ON ingest_jobs(tenant_id, created_at);
CREATE INDEX idx_ingest_jobs_status ON ingest_jobs(status);

-- Rule Definitions (DSL-based rules)
CREATE TABLE rule_definitions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    condition_dsl TEXT NOT NULL,
    params JSONB,
    severity alert_severity_type DEFAULT 'MEDIUM',
    category VARCHAR(100),  -- e.g., SPIKE, STRUCTURING, PEP_RISK, etc.
    status rule_status_type DEFAULT 'ACTIVE',
    version INT DEFAULT 1,
    created_by UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rules_tenant ON rule_definitions(tenant_id);
CREATE INDEX idx_rules_status ON rule_definitions(tenant_id, status);

-- Rule Execution Logs (audit trail)
CREATE TABLE rule_execution_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    rule_id UUID NOT NULL REFERENCES rule_definitions(id),
    event_id UUID NOT NULL,
    matched BOOLEAN,
    context JSONB,  -- { "features": {...}, "event": {...} }
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rule_exec_logs_tenant ON rule_execution_logs(tenant_id);
CREATE INDEX idx_rule_exec_logs_event ON rule_execution_logs(event_id);

-- Alerts (generated by rules and ML)
CREATE TABLE alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    player_id VARCHAR(255) NOT NULL,  -- External player ID
    player_cpf VARCHAR(50),  -- Masked in app, full in DB with PII encryption
    severity alert_severity_type NOT NULL,
    status alert_status_type DEFAULT 'NEW',
    alert_type VARCHAR(100),  -- RULE, ANOMALY, COMPOSITE
    rule_id UUID REFERENCES rule_definitions(id),
    anomaly_score FLOAT,
    evidence JSONB,  -- { "triggered_rules": [...], "features": {...}, "anomaly_drivers": [...] }
    assigned_to UUID REFERENCES users(id),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alerts_tenant ON alerts(tenant_id, created_at);
CREATE INDEX idx_alerts_status ON alerts(tenant_id, status);
CREATE INDEX idx_alerts_player ON alerts(tenant_id, player_id);

-- Cases (grouping related alerts)
CREATE TABLE cases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    player_id VARCHAR(255) NOT NULL,
    player_cpf VARCHAR(50),
    status case_status_type DEFAULT 'OPEN',
    severity alert_severity_type,
    risk_score FLOAT,
    assigned_to UUID REFERENCES users(id),
    description TEXT,
    created_by UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cases_tenant ON cases(tenant_id, created_at);
CREATE INDEX idx_cases_status ON cases(tenant_id, status);
CREATE INDEX idx_cases_player ON cases(tenant_id, player_id);
CREATE INDEX idx_cases_assigned ON cases(tenant_id, assigned_to);

-- Case Events (audit trail and timeline)
CREATE TABLE case_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    event_type VARCHAR(100),  -- NOTE, DECISION, EVIDENCE_ADDED, STATUS_CHANGED
    created_by UUID NOT NULL REFERENCES users(id),
    content TEXT,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_case_events_case ON case_events(case_id, created_at);

-- Evidence (attachments to cases)
CREATE TABLE case_evidence (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(512),  -- S3/MinIO path
    file_size_bytes BIGINT,
    mime_type VARCHAR(100),
    uploaded_by UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_evidence_case ON case_evidence(case_id);

-- Report Packages (generated for submission)
CREATE TABLE report_packages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    case_id UUID NOT NULL REFERENCES cases(id),
    player_id VARCHAR(255),
    report_type VARCHAR(100),  -- SAR, SAT, CLOSURE_REPORT
    payload JSONB NOT NULL,  -- Complete report data (masked PII in UI)
    status VARCHAR(50) DEFAULT 'DRAFT',  -- DRAFT, GENERATED, EXPORTED
    generated_by UUID NOT NULL REFERENCES users(id),
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    exported_at TIMESTAMP,
    export_format VARCHAR(20),  -- JSON, CSV, PDF
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_reports_tenant ON report_packages(tenant_id);
CREATE INDEX idx_reports_case ON report_packages(case_id);

-- Audit Log (compliance)
CREATE TABLE audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id),
    action VARCHAR(255) NOT NULL,  -- CREATE_RULE, UPDATE_ALERT, GENERATE_REPORT, etc.
    entity_type VARCHAR(100),
    entity_id UUID,
    changes JSONB,  -- { "before": {...}, "after": {...} }
    ip_address VARCHAR(50),
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_tenant ON audit_logs(tenant_id, created_at);
CREATE INDEX idx_audit_logs_user ON audit_logs(user_id, created_at);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);

-- Model Registry (ML model versions)
CREATE TABLE model_registry (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    model_type VARCHAR(100),  -- ISOLATION_FOREST, etc.
    model_version INT NOT NULL,
    artifact_path VARCHAR(512),  -- S3/MinIO path
    trained_at TIMESTAMP,
    dataset_window_days INT,
    metrics JSONB,  -- { "f1_score": 0.85, ... }
    is_active BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(tenant_id, model_type, model_version)
);

CREATE INDEX idx_model_registry_tenant ON model_registry(tenant_id, model_type);

-- ===================== FUNCTIONS =====================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER tenants_updated_at_trigger BEFORE UPDATE ON tenants
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER users_updated_at_trigger BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER mapping_configs_updated_at_trigger BEFORE UPDATE ON mapping_configs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER rule_definitions_updated_at_trigger BEFORE UPDATE ON rule_definitions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER alerts_updated_at_trigger BEFORE UPDATE ON alerts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER cases_updated_at_trigger BEFORE UPDATE ON cases
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ===================== INITIAL DATA =====================

-- Insert default tenants
INSERT INTO tenants (name, description)
VALUES 
    ('OperadorA', 'Operadora de Apostas Alpha - Teste'),
    ('OperadorB', 'Operadora de Apostas Beta - Teste');

-- Insert default users
INSERT INTO users (tenant_id, username, email, password_hash, role)
SELECT t.id, 'admin_a', 'admin@operadora-a.com', '$2b$12$placeholder_hash_admin_a', 'ADMIN'
FROM tenants WHERE name = 'OperadorA'
UNION ALL
SELECT t.id, 'analyst_a', 'analyst@operadora-a.com', '$2b$12$placeholder_hash_analyst_a', 'AML_ANALYST'
FROM tenants WHERE name = 'OperadorA'
UNION ALL
SELECT t.id, 'auditor_a', 'auditor@operadora-a.com', '$2b$12$placeholder_hash_auditor_a', 'AUDITOR'
FROM tenants WHERE name = 'OperadorA'
UNION ALL
SELECT t.id, 'admin_b', 'admin@operadora-b.com', '$2b$12$placeholder_hash_admin_b', 'ADMIN'
FROM tenants WHERE name = 'OperadorB'
UNION ALL
SELECT t.id, 'analyst_b', 'analyst@operadora-b.com', '$2b$12$placeholder_hash_analyst_b', 'AML_ANALYST'
FROM tenants WHERE name = 'OperadorB'
UNION ALL
SELECT t.id, 'auditor_b', 'auditor@operadora-b.com', '$2b$12$placeholder_hash_auditor_b', 'AUDITOR'
FROM tenants WHERE name = 'OperadorB';

-- ===================== VIEWS FOR QUERY EFFICIENCY =====================

CREATE VIEW active_rules_by_tenant AS
SELECT 
    r.id,
    r.tenant_id,
    r.name,
    r.condition_dsl,
    r.severity,
    r.category,
    t.name as tenant_name
FROM rule_definitions r
JOIN tenants t ON r.tenant_id = t.id
WHERE r.status = 'ACTIVE';

CREATE VIEW recent_alerts AS
SELECT 
    a.id,
    a.tenant_id,
    a.player_id,
    a.severity,
    a.status,
    a.alert_type,
    a.created_at,
    t.name as tenant_name,
    COUNT(*) OVER (PARTITION BY a.player_id) as player_alert_count
FROM alerts a
JOIN tenants t ON a.tenant_id = t.id
WHERE a.created_at > CURRENT_TIMESTAMP - INTERVAL '30 days'
ORDER BY a.created_at DESC;

-- ===================== ROW-LEVEL SECURITY (RLS) =====================

ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE rule_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies (enforced at application level for simplicity; enable if needed)
-- CREATE POLICY tenant_isolation ON tenants USING (id = current_setting('app.tenant_id')::uuid);
-- CREATE POLICY user_isolation ON users USING (tenant_id = current_setting('app.tenant_id')::uuid);
-- etc.

-- ===================== GRANT PERMISSIONS =====================

GRANT CONNECT ON DATABASE betaml_dev TO betaml;
GRANT USAGE ON SCHEMA public TO betaml;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO betaml;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO betaml;
