[pytest]
testpaths =
	tests/unit
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
addopts = -v --tb=short

filterwarnings =
    ignore::DeprecationWarning
    ignore::requests.exceptions.RequestsDependencyWarning
    ignore:.*doesn't match a supported version.*:Warning:requests
