{{- if .Values.streamProcessor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "betaml.fullname" . }}-stream-processor
  labels:
    {{- include "betaml.labels" . | nindent 4 }}
    app.kubernetes.io/component: stream-processor
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.streamProcessor.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.streamProcessor.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "betaml.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: stream-processor
{{- end }}
